# ==========================================
# CONFIGURACIÓN BÁSICA
# ==========================================
spring.application.name=inventario
server.port=8082

# ==========================================
# BASE DE DATOS MYSQL - AIVEN
# ==========================================
spring.datasource.url=jdbc:mysql://mysql-2bd6720e-duocuc-7153.c.aivencloud.com:28226/syncro_inventario?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_Y-yThiMj7gNupW-9yR7
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Forzar el dialecto para evitar el error del log
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Esto ayuda a que Spring no falle si la conexión tarda un poco
spring.datasource.hikari.initialization-fail-timeout=0
# ==========================================
# SEGURIDAD JWT
# ==========================================
# Clave secreta (debe tener al menos 32 caracteres para HS256)
jwt.secret=estaEsUnaClaveMuySecretaDeAlMenos32CaracteresParaHS256
# Expiración: 86400000 ms = 24 horas
jwt.expiration=86400000

# ==========================================
# CONFIGURACIÓN DE LOGS
# ==========================================
logging.level.com.syncro.inventario=DEBUG

# ==========================================
# CONFIGURACIÓN RABBITMQ (CloudAMQP)
# ==========================================
# Reemplaza con tus credenciales de CloudAMQP
spring.rabbitmq.host=jaragua-01.lmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=wvbylqxy
spring.rabbitmq.password=7fIVhAdUUie_0gzkpCAJvW-v1VuLlGt9
spring.rabbitmq.virtual-host=wvbylqxy

# ==========================================
# PERFIL ACTIVO
# ==========================================
spring.profiles.active=dev

# ==========================================
# CONFIGURACIÓN SWAGGER / OPENAPI
# ==========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true